src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\OneToMany(targetEntity: PlayerSession::class, mappedBy: 'session', orphanRemoval: true)]
    private Collection $playerSessions;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $game = null;

    public function __construct()
    {
        $this->playerSessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }
    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;

        return $this;
    }

    /**
     * @return Collection<int, PlayerSession>
     */
    public function getPlayerSessions(): Collection
    {
        return $this->playerSessions;
    }

    public function addPlayerSession(PlayerSession $playerSession): static
    {
        if (!$this->playerSessions->contains($playerSession)) {
            $this->playerSessions->add($playerSession);
            $playerSession->setSession($this);
        }

        return $this;
    }

    public function removePlayerSession(PlayerSession $playerSession): static
    {
        if ($this->playerSessions->removeElement($playerSession)) {
            // set the owning side to null (unless already changed)
            if ($playerSession->getSession() === $this) {
                $playerSession->setSession(null);
            }
        }

        return $this;
    }



    /**
     * @return PlayerSession
     */
    public function getWinningPlayerSession()
    {   
        foreach ($this->playerSessions as $key => $playerSession) {
            if ($playerSession->isIsWinner()){
                return $playerSession;
            }
        }  
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Game;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('game', EntityType::class, [
                'class' => Game::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\PlayerSession;
use App\Form\SessionType;
use App\Form\SessionPlayerLightType;
use App\Repository\SessionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/session')]
class SessionController extends AbstractController
{
    #[Route('/', name: 'app_session_index', methods: ['GET'])]
    public function index(SessionRepository $sessionRepository): Response
    {
        return $this->render('session/index.html.twig', [
            'sessions' => $sessionRepository->findAllWithFullSessionInfo(),
        ]);
    }

    #[Route('/new', name: 'app_session_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $session = new Session();
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($session);
            $entityManager->flush();

            return $this->redirectToRoute('app_session_show',  array('id'=>$session->getId()), Response::HTTP_SEE_OTHER);
        }

        return $this->render('session/new.html.twig', [
            'session' => $session,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_show', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function show(int $id, Request $request, EntityManagerInterface $entityManager,SessionRepository $sessionRepository): Response
    {   
        $session = $sessionRepository->findSessionWithFullSessionInfo($id);
        $playerSession = new PlayerSession();
        $playerSession->setSession($session);
        $leftovers = $entityManager->getRepository('App\Entity\Player')->findPlayersNotAssignedToSession($session);
        $form = $this->createForm(SessionPlayerLightType::class, $playerSession, array('leftovers'=>$leftovers));
        
        return $this->render('session/show.html.twig', [
            'session' => $session,
            'player_form' => $form
        ]);
    }

    #[Route('/{id}/edit', name: 'app_session_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Session $session, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_session_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('session/edit.html.twig', [
            'session' => $session,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_delete', methods: ['POST'])]
    public function delete(Request $request, Session $session, EntityManagerInterface $entityManager): Response
    {

        $playerSession = new PlayerSession();
        $playerSession->setSession($session);
        $form = $this->createForm(SessionPlayerLightType::class, $playerSession);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playerSession->setGameRole($entityManager->find('App\Entity\GameRole', $request->request->get('game_role_id')));
            $entityManager->persist($playerSession);
            $entityManager->flush();
            return $this->redirectToRoute('app_session_show', array('id'=>$session->getId()), Response::HTTP_SEE_OTHER);
        }elseif ($this->isCsrfTokenValid('delete'.$session->getId(), $request->request->get('_token'))) {
            $entityManager->remove($session);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_session_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/session/_delete_form.html.twig
<form method="post" action="{{ path('app_session_delete', {'id': session.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/session/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/session/_player_form.html.twig
{{ form_start(player_form) }}
   
<input type="hidden" name="game_role_id" value="{{ role.id }}">
    {{ form_widget(player_form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(player_form) }}

templates/session/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Session{% endblock %}

{% block body %}
    <h1>Edit Session</h1>

    {{ include('session/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_session_index') }}">back to list</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}

<script src="https://cdn.jsdelivr.net/npm/chart.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0" defer></script>
<script src="/client.js" defer></script>
{% endblock %}

{% block title %}Session index{% endblock %}

{% block body %}
    <h1>Session index</h1>
    <div class="row">
        <div class="col">
            <canvas id="factionPie"></canvas>
        </div>
        <div class="col">
            <canvas id="combinedRadar"></canvas>
        </div>
        <div class="col">
            <canvas id="playerPie"></canvas>
        </div>
    </div>

    <div class="row">
        <div class="col">
            
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Winning Player</th>
                <th>Winning Faction</th>
            </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                <td>
                    {{ session.id }}<br/>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('app_session_edit', {'id': session.id}) }}">edit</a>
                    {% endif %}</td>
                <td>{{ session.date ? session.date|date('Y-m-d H:i:s') : '' }}</td>
                {% if session.winningPlayerSession %}
                <td><a href="{{ path('app_player_show', {'id': session.winningPlayerSession.player.id}) }}">{{ session.winningPlayerSession.player.name }}</a></td>
                <td><a href="{{ path('app_game_role_show', {'id': session.winningPlayerSession.gameRole.id}) }}">{{ session.winningPlayerSession.gameRole.name }}</td>
                {% else %}
                    <td colspan="2"><a href="{{ path('app_session_show', {'id': session.id}) }}">Mark Players Now!</a></td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('app_session_new') }}" class="btn btn-primary">Create new</a>
    {% endif %}
    </div>
</div>
<script>
   const sessions = [
    {% for session in sessions %}
        {
            "winning_faction":"{{session.winningPlayerSession.gameRole.name}}",
            "winning_player":"{{session.winningPlayerSession.player.name}}"
        },
    {% endfor %}
]   ;

document.addEventListener("DOMContentLoaded", async function(event) {
    console.log(sessions)
    updateChart(sessions)
});
</script>
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Session{% endblock %}

{% block body %}
    <h1>Create new Session</h1>

    {{ include('session/_form.html.twig') }}

    <a href="{{ path('app_session_index') }}">back to list</a>
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Session{% endblock %}

{% block body %}
    <h1>Session {{ session.id }} Details - {{ session.date ? session.date|date('M d, Y') : '' }}</h1>

    <div class="row">
        <div class="col-12">
        <h3>Winner's Circle</h3>
        {% if session.getWinningPlayerSession %}
                <p><strong>{{ session.getWinningPlayerSession.gameRole.name }} </strong> were victorious led by <strong>{{ session.getWinningPlayerSession.player.name }} </strong></p>      
        {% else %}
            <p><strong>Awaiting Outcome...</strong></p>
            <p>Enter players below and be sure to mark a winner!</p>


        {% endif %}
        </div>
    </div>
    <div class="row">
        <h3>Player Roles</h3>
        <table class="table">
            <tbody>
                {% set gameRolesUsed = session.game.gameRoles %}
                {% for playerSession in session.playerSessions %}
                    {% set gameRolesUsed = gameRolesUsed|filter((v, k) => v != playerSession.gameRole) %}
                    <tr>
                        <th>{% if playerSession.isWinner %}👑 {% endif %}<a href="{{ path('app_game_role_show', {'id': playerSession.gameRole.id}) }}">{{ playerSession.gameRole.name }}</a></th>
                        <td>{{ playerSession.player.name }} : {{ playerSession.score }} 
                            <a href="{{ path('app_player_session_edit', {'id': playerSession.id,'return':'app_session_show'}) }}">edit</a></td>
                    </tr>
                {% endfor %}
                {% if (gameRolesUsed|length) > 0 %}
                    {% set role = gameRolesUsed|first %}
                    <tr>
                        <th>{{role.name}}</th>
                        <td>{{ include('session/_player_form.html.twig') }}</td>
                    </tr>
                    
                {% endif %}
                
            </tbody>
        </table>
    </div>
    <div class="row">

        <a href="{{ path('app_session_index') }}">back to list</a>

        <a href="{{ path('app_session_edit', {'id': session.id}) }}">edit</a>
    </div>


    {{ include('session/_delete_form.html.twig') }}
{% endblock %}